from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Protocol
from urllib.parse import urlparse
from urllib.request import Request, urlopen

from d2t_agent.models import FactBundle
from d2t_agent.renderers import deterministic_report, evidence_markdown


class ReportProvider(Protocol):
    def render(self, facts: FactBundle, title: str) -> str: ...


@dataclass(frozen=True)
class DeterministicProvider:
    def render(self, facts: FactBundle, title: str) -> str:
        return deterministic_report(facts, title)


@dataclass(frozen=True)
class OllamaProvider:
    """Optional local-only narrative provider; computed evidence remains deterministic."""

    model: str = "llama3.2"
    endpoint: str = "http://127.0.0.1:11434/api/generate"
    timeout_seconds: int = 60

    def __post_init__(self) -> None:
        parsed = urlparse(self.endpoint)
        if parsed.scheme != "http" or parsed.hostname not in {"127.0.0.1", "localhost", "::1"}:
            raise ValueError("Ollama endpoint must be a local HTTP address")
        if parsed.username or parsed.password:
            raise ValueError("Ollama endpoint must not contain credentials")
        if not self.model.strip():
            raise ValueError("Ollama model must be non-empty")

    def render(self, facts: FactBundle, title: str) -> str:
        evidence = json.dumps(facts.to_dict(), indent=2, sort_keys=True)
        prompt = (
            "Write a concise executive summary using only the JSON evidence below. "
            "Do not add causes, forecasts, recommendations, or numbers absent from the evidence. "
            "Return three to six Markdown bullets.\n\n" + evidence
        )
        payload = json.dumps({"model": self.model, "prompt": prompt, "stream": False}).encode("utf-8")
        request = Request(self.endpoint, data=payload, headers={"Content-Type": "application/json"})
        try:
            with urlopen(request, timeout=self.timeout_seconds) as response:
                result = json.loads(response.read().decode("utf-8"))
        except OSError as exc:
            raise RuntimeError(f"Local Ollama request failed: {exc}") from exc
        narrative = result.get("response") if isinstance(result, dict) else None
        if not isinstance(narrative, str) or not narrative.strip():
            raise RuntimeError("Local Ollama returned no narrative")
        if len(narrative) > 20_000:
            raise RuntimeError("Local Ollama narrative exceeded the 20,000-character limit")
        return "\n".join(
            [
                f"# {title}",
                "",
                "> Narrative wording was generated by a local Ollama model; all numeric evidence below is computed deterministically.",
                "",
                "## Local model narrative",
                "",
                narrative.strip(),
                "",
                evidence_markdown(facts),
                "",
            ]
        )

